FROM cmelab/gpuconda:latest

#ENV CONDA_OVERRIDE_CUDA=10.2

RUN conda update -n base -c defaults conda && \
    conda info && \
    conda install mamba -n base -c conda-forge && \
    mamba install -c conda-forge hoomd python && \
    mamba install -c conda-forge mbuild gsd ipython ipykernel mdanalysis physical_validation  ipywidgets widgetsnbextension freud cassandra foyer py3Dmol nglview && \ 
    mamba install -c conda-forge vim openssh && \
    conda install gromacs=*=mpi* -c bioconda -c conda-forge  
#jupyter-nbextension enable nglview --py --sys-prefix
