FROM cmelab/gpuconda:latest

RUN conda update -n base -c defaults conda && \
    conda info && \
    conda install mamba -n base -c conda-forge && \
    mamba install -c bioconda -c conda-forge python=3.8  vim openssh mbuild gsd ipython ipykernel mdanalysis foyer ipywidgets widgetsnbextension freud py3Dmol ele mdtraj rdkit scipy networkx intermol numpy packmol parmed pip physical_validation dask matplotlib jupyter seaborn unyt constrainmol pytest pandas garnett pycifrw ase 

# configure unprivileged user
RUN useradd --create-home --shell /bin/bash icomse-software 
USER icomse-software:icomse-software
