FROM tensorflow/tensorflow:2.4.1

# Install system dependencies
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        cmake \
        curl \
        git \
        gnupg \
        libfreetype6-dev \
        libhdf5-serial-dev \
        libtbb-dev \
        libzmq3-dev \
    && apt-get clean

WORKDIR /opt

# Make RUN commands use `bash --login`: -- fixes conda init
# https://pythonspeed.com/articles/activate-conda-dockerfile/
SHELL ["/bin/bash", "--login", "-c"]

# Prevent python from loading packages from outside the container
# default empty pythonpath
ENV PYTHONPATH=/ignore/pythonpath

# Install HOOMD and tensorflow deps
RUN python3 -m pip install numpy==1.19.5 wheel && \
    python3 --version && \
    python3 -m pip install --no-deps keras_preprocessing

# Clone HOOMD
ENV HOOMD_TAG=v2.9.4

RUN git clone --recursive https://github.com/glotzerlab/hoomd-blue.git -b $HOOMD_TAG --single-branch && \
    cd hoomd-blue && \
    git submodule update

# Link HOOMD-TF in HOOMD/hoomd modules
RUN git clone -b cg_properties_update --single-branch https://github.com/ur-whitelab/hoomd-tf.git && \
    ln -s /opt/hoomd-tf/htf /opt/hoomd-blue/hoomd
#RUN find /usr -name "*tensorflow*" && python3 --version && ffksdf
# Compile HOOMD with HOOMD-TF
RUN cd hoomd-blue && \
    mkdir build && \
    cd build && \
    cmake ../ -DENABLE_MPI=OFF \
              -DENABLE_CUDA=OFF \
              -DPYTHON_EXECUTABLE=$(which python3) \
              -DCMAKE_C_COMPILER=$(which gcc) \
              -DCMAKE_CXX_COMPILER=$(which g++) \
              -DCMAKE_INSTALL_PREFIX=$(python3 -c "import site; print(site.getsitepackages()[0])") \
              -DBUILD_HPMC=OFF \
              -DBUILD_JIT=OFF \ 
              -DBUILD_METAL=OFF \ 
              -DBUILD_DEM=OFF \
              -DBUILD_CGCMM=OFF \
              -DBUILD_DEPRECATED=OFF \
              -DBUILD_MPCD=OFF && \
    make && \
    make install

