FROM cmelab/gpuconda:latest

ENV CONDA_OVERRIDE_CUDA=10.2

RUN conda update -n base -c defaults conda && \
    conda info && \
    conda install mamba -n base -c conda-forge && \
    mamba install -c conda-forge hoomd=3*=*gpu* cudatoolkit=10.2 python && \
    mamba install -c conda-forge mbuild gsd cassandra jupyter foyer && \
    mamba install -c conda-forge freud #&& \
    conda install -c bioconda gromacs
#mamba install -c conda-forge nglview mdanalysis
#manba install -c bioconda gromacs  

