FROM cmelab/gpuhoomdtf:latest

# Install prerequisite packages for HTF and ULI
RUN python -m pip install mbuild matplotlib foyer gsd parmed scipy signac signac-flow networkx ele lark deepsmiles
RUN git clone --single-branch https://github.com/RainierBarrett/uli-init --branch htf-cg && \
    cd uli-init && \
    conda env update base -f environment-nohoomd.yml && \
    conda install -c conda-forge openmm lxml oset
RUN cd uli-init && \
    pip install -e .
    