from ubuntu:18.04

# NOTE: *before* you run this container you will need to expose your host's X server, e.g.:
# sudo xhost +local:root
# when you run it, mount your X11 Unix directory, set DISPLAY, turn off qt's shared memory extension:
# docker run --rm -it --gpus all -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -e QT_X11_NO_MITSHM=1

# Install system dependencies
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# install build reqs from https://gitlab.com/stuko/ovito/-/blob/v3.0.0/doc/manual/development/build_linux.docbook
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        cmake \
        curl \
        build-essential \
        git \
        cmake-curses-gui \
        qt5-default \
        libqt5svg5-dev \
        libboost-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavfilter-dev \
        libavformat-dev \
        libavresample-dev \
        libavutil-dev \
        libglvnd0 \
        libgl1 \
        libglx0 \
        libegl1 \
        libglvnd-dev \
        libgl1-mesa-dev \
        libegl1-mesa-dev \
        libxext6 \
        libx11-6 \
        libswscale-dev \
        libnetcdf-dev \
        libhdf5-dev \
        libhdf5-serial-dev \
        libssh-dev \
        xsltproc \
        docbook-xml \
    && apt-get clean

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all

# get frozen version before "Pro" ovito
RUN git clone --single-branch -b v3.0.0 https://gitlab.com/stuko/ovito.git && \
    mkdir ovito/build

WORKDIR ovito/build

RUN cmake .. -DCMAKE_BUILD_TYPE=Release

RUN make -j4 