FROM cmelab/gpuconda:latest

RUN conda update -n base -c defaults conda && \
    conda info && \
    conda install libarchive mamba -n base -c conda-forge && \
    mamba install -c conda-forge hoomd=4.7.0

#RUN conda update -n base -c defaults conda && \
#    conda info && \
#    conda install mamba -n base -c conda-forge && \
#    conda install -c conda-forge python=3.8 vim openssh mbuild gsd ipython ipykernel mdanalysis foyer ipywidgets scipy numpy physical_validation matplotlib jupyter pandas pycifrw ase nglview 

# configure unprivileged user
RUN useradd --create-home --shell /bin/bash icomse-software 
USER icomse-software:icomse-software
