FROM glotzerlab/software

RUN mamba install -c conda-forge vim openssh mbuild gsd ipython ipykernel mdanalysis foyer ipywidgets scipy numpy physical_validation matplotlib jupyter pandas pycifrw ase nglview 


